### ISSUE TITLE
Environment.ProcessorCount will change in .NET 6

### ISSUE THREAD

**Issue by taspeotis** [sdrapkin/SecurityDriven.Core#5]
Hi,

I find [your implementation](https://github.com/sdrapkin/SecurityDriven.Core/blob/64ab11c8850e6473d780d9b7fd16ddc702494c96/SecurityDriven.Core/RNGCryptoRandom.cs#L21) of per-thread caching clever and interesting. I think there is a pathological edge case in .NET 5 and earlier and a more likely edge case in .NET 6 that will cause a problem, however.

.NET 6 changes `Environment.ProcessorCount` to return a number less than the number of processors [in two cases](https://docs.microsoft.com/en-us/dotnet/api/system.environment.processorcount?view=net-5.0#remarks):

> * If the process is running with CPU affinity, the number of processors that the process is affinitized to.
> * If the process is running with a CPU utilization limit, the CPU utilization limit rounded up to the next whole number.

In this case I believe `Thread.GetCurrentProcessorId` can return a number greater than `Environment.ProcessorCount` (especially in the case that the process affinity is set to, say, the seventh and eight CPU cores).

In all versions of .NET "The value returned by this API is fixed at .NET runtime startup for the process lifetime" and in certain virtualisation environments support [hot add vCPU](https://kb.vmware.com/s/article/2051989) so more processors could be added after the application starts.

In any case, if either of the above situations transpires then [this line](https://github.com/sdrapkin/SecurityDriven.Core/blob/64ab11c8850e6473d780d9b7fd16ddc702494c96/SecurityDriven.Core/RNGCryptoRandom.cs#L50) will throw an `IndexOutOfRangeException`.

Please note I do not have .NET 6 or virtualization software with hot add vCPU on hand, so I apologise if this is a hypothetical. The breaking change documentation for .NET 6 is [here](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/environment-processorcount-on-windows) and it suggests this might already be a problem when running on Unix-based hosts.

**Comment by sdrapkin** [comment]
@taspeotis Thanks for raising this. What would be your suggestion for the best way to prepare for the change? Some ideas:
1. Modulo the `Thread.GetCurrentProcessorId()` by the `ProcessorCount` buckets (`%` might be expensive)
2. Use the min of `Thread.GetCurrentProcessorId()` and `ProcessorCount` (faster than mod? uneven/hot bucket?)
3. Hopefully a better idea? This is on a hot-path...
